version: '3'

services:
  web:
    build: .
    ports:
     - "80:8080"
    depends_on:
      - mysql
    networks:
      - greatapp_net
    command:  ["java", "-Dspring.profiles.active=production", 
              "-jar", "spring-boot-and-react-app-0.1.0.jar"]
